name: applied_bayes

channels:
  - conda-forge
dependencies:
  - arviz
  - python
  - ipython
  - ipywidgets
  - jax
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - numba
  - numpy
  - patsy
  - pip
  - plotly
  - polars
  - preliz
  - pymc
  - pymc-extras
  - pydot
  - python-graphviz
  - scipy
  - seaborn
  - setuptools
  - watermark
  - xarray
  - xlrd
