[project]
authors = [
    "Chris Fonnesbeck <fonnesbeck@gmail.com>",
]
channels = ["conda-forge"]
description = "Applied Bayesian Modeling in Python"
name = "applied_bayes"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
ipython = "*"
ipywidgets = "*"
jupyter_client = "*"
jupyter_core = "*"
jupyterlab = "*"
numpy = "*"
pandas = "*"
patsy = "*"
pip = "*"
polars = "*"
pyarrow = "*"
pymc = "*"
pydot = "*"
python-graphviz = "*"
scipy = "*"
seaborn = "*"
setuptools = "*"
watermark = "*"
matplotlib = "*"
preliz = ">=0.20.0,<0.21"
nutpie = ">=0.15.2,<0.16"
numba = ">=0.61.2,<0.62"
plotly = ">=6.3.0,<7"
numpyro = ">=0.19.0,<0.20"
pymc-extras = ">=0.4.0,<0.5"
jax = ">=0.7.0,<0.8"
ruff = ">=0.12.11,<0.13"

